version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: contactdb
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/contactdb

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo

  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./nagios/etc:/usr/local/nagios/etc
      - ./nagios/var:/usr/local/nagios/var
      - ./nagios/libexec:/usr/local/nagios/libexec
    environment:
      - NAGIOSADMIN_USER=nagiosadmin
      - NAGIOSADMIN_PASS=admin123

volumes:
  mongo_data: